---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - $HOME/.npm
  - .eslintcache
  - node_modules
matrix:
  fast_finish: true
  include:
    #
    - node_js: '6'
before_install:
  - "npm install -g npm"
