//

export const HAS_RUNTIME_METADATA_RESOLVER_HOOK = '__HAS_RUNTIME_METADATA_RESOLVER_HOOK__' // Make this a symbol
export const IS_PART_OF_THE_DEBUGGER = '__IS_PART_OF_THE_DEBUGGER__'
export const BATSCANNER_ID = '__BATSCANNER_ID__'
export const BATSCANNER_RECORD = '__BATSCANNER_RECORD__'
